name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: self-hosted

    environment: production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build and Deploy using Docker Compose
      - name: Deploy with Docker Compose
        run: |
          echo "${{secrets.TEST_SECRET}}"
          echo "${{env.TEST_VARIABLE}}"